# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smallcage}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["SAITO Toshihiro", "gommmmmm", "KOSEKI Kengo"]
  s.date = %q{2009-11-13}
  s.default_executable = %q{smc}
  s.description = %q{SmallCage is a simple, but powerful website generator. It converts content and template files, which has common elements in a website, to a plain, static website. No database, no application container, and no repeat in many pages is needed. You can keep your site well with very little work.}
  s.email = %q{smallcage@googlegroups.com}
  s.executables = ["smc"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "License.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/smc",
     "lib/smallcage.rb",
     "lib/smallcage/application.rb",
     "lib/smallcage/commands/auto.rb",
     "lib/smallcage/commands/base.rb",
     "lib/smallcage/commands/clean.rb",
     "lib/smallcage/commands/export.rb",
     "lib/smallcage/commands/import.rb",
     "lib/smallcage/commands/manifest.rb",
     "lib/smallcage/commands/server.rb",
     "lib/smallcage/commands/update.rb",
     "lib/smallcage/commands/uri.rb",
     "lib/smallcage/document_path.rb",
     "lib/smallcage/erb_base.rb",
     "lib/smallcage/http_server.rb",
     "lib/smallcage/loader.rb",
     "lib/smallcage/misc.rb",
     "lib/smallcage/renderer.rb",
     "lib/smallcage/resources/Manifest.erb",
     "lib/smallcage/resources/auto.html",
     "lib/smallcage/runner.rb",
     "lib/smallcage/update_list.rb",
     "lib/smallcage/version.rb",
     "project/base/_smc/helpers/base_helper.rb",
     "project/base/_smc/helpers/site_helper.rb",
     "project/base/_smc/templates/default.rhtml",
     "project/base/_smc/templates/footer.rhtml",
     "project/base/_smc/templates/header.rhtml",
     "project/bluecloth/_smc/helpers/blue_cloth_helper.rb",
     "project/bluecloth/_smc/templates/markdown.rhtml",
     "project/cache/_smc/filters/cache_filter.rb",
     "project/cache/_smc/filters/filters.yml",
     "project/cache/_smc/rakelib/cache.rake",
     "project/gdata/_smc/rakelib/gdata.rake",
     "project/lang/_smc/helpers/lang_helper.rb",
     "project/lang/_smc/templates/other_lang.rhtml",
     "project/news/_smc/helpers/news_helper.rb",
     "project/nkf/_smc/filters/filters.yml",
     "project/nkf/_smc/filters/nkf_filter.rb",
     "project/nkf/_smc/helpers/nkf_helper.rb",
     "project/rake/_smc/Rakefile",
     "project/rake/_smc/rakelib/csv.rake",
     "project/rake/_smc/rakelib/svn.rake",
     "project/redcloth/_smc/helpers/red_cloth_helper.rb",
     "project/redcloth/_smc/templates/textile.rhtml",
     "project/relpath/_smc/filters/filters.yml",
     "project/relpath/_smc/filters/relpath_filter.rb",
     "project/standard/_dir.smc",
     "project/standard/_smc/helpers/menu_helper.rb",
     "project/standard/_smc/templates/default.rhtml",
     "project/standard/_smc/templates/footer.rhtml",
     "project/standard/_smc/templates/header.rhtml",
     "project/standard/_smc/templates/menu.rhtml",
     "project/standard/_smc/templates/redirect.rhtml",
     "project/standard/_smc/templates/sidebar.rhtml",
     "project/standard/_smc/templates/topic_path.rhtml",
     "project/standard/common/css/default.css",
     "project/standard/common/css/print.css",
     "project/standard/index.html.smc",
     "project/standard/sample/_dir.smc",
     "project/standard/sample/index.html.smc",
     "project/standard/sample/redirect.html.smc",
     "project/standard/sample/sub/_dir.smc",
     "project/standard/sample/sub/contents.html.smc",
     "project/standard/sample/sub/index.html.smc",
     "project/tutorial/_smc/helpers/sample_helper.rb",
     "project/tutorial/_smc/templates/default.rhtml",
     "project/tutorial/_smc/templates/include1.rhtml",
     "project/tutorial/_smc/templates/include2.rhtml",
     "project/tutorial/sample.txt.smc",
     "project/tutorial/sample2.txt.smc",
     "project/tutorial2/_smc/helpers/priority_sample_helper.rb",
     "project/tutorial2/_smc/templates/priorities.rhtml",
     "project/tutorial2/_smc/templates/priority1.rhtml",
     "project/tutorial2/_smc/templates/priority2.rhtml",
     "project/tutorial2/_smc/templates/priority3.rhtml",
     "project/tutorial2/_smc/templates/smc_variables.rhtml",
     "project/tutorial2/tutorial2/_dir.smc",
     "project/tutorial2/tutorial2/priorities.txt.smc",
     "project/tutorial2/tutorial2/vars.txt.smc",
     "smallcage.gemspec",
     "spec/data/htdocs1/_dir.smc",
     "spec/data/htdocs1/_smc/.gitignore",
     "spec/data/htdocs1/_smc/filters/filters.yml",
     "spec/data/htdocs1/a/b/c/index.html.smc",
     "spec/data/htdocs2/_smc/filters/filters.yml",
     "spec/data/htdocs2/_smc/templates/dummy.rhtml",
     "spec/data/htdocs2/a/b/c/test.html",
     "spec/data/htdocs2/a/b/test.html",
     "spec/data/htdocs2/a/test.html.smc",
     "spec/data/htdocs3/_dir.smc",
     "spec/data/htdocs3/_local.smc",
     "spec/data/htdocs3/_smc/.gitignore",
     "spec/data/htdocs3/a/b/_dir.smc",
     "spec/data/htdocs3/a/b/_local.smc",
     "spec/data/htdocs3/a/b/c/_local.smc",
     "spec/data/htdocs3/a/b/c/index.html.smc",
     "spec/data/htdocs3/a/index.html.smc",
     "spec/data/htdocs3/ab/index.html.smc",
     "spec/data/htdocs3/abc/index.html.smc",
     "spec/data/multifiles/_dir.smc",
     "spec/data/multifiles/_smc/templates/default.rhtml",
     "spec/data/multifiles/_smc/templates/items.rhtml",
     "spec/data/multifiles/_smc/templates/items.uri.rhtml",
     "spec/data/multifiles/index.html.smc",
     "spec/data/multifiles/items/index.html.smc",
     "spec/data/updatelists/list1.yml",
     "spec/document_path_spec.rb",
     "spec/export_spec.rb",
     "spec/import_spec.rb",
     "spec/loader_spec.rb",
     "spec/manifest_spec.rb",
     "spec/misc_spec.rb",
     "spec/smallcage_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/update_list_spec.rb",
     "spec/update_spec.rb",
     "spec/uri_spec.rb"
  ]
  s.homepage = %q{http://www.smallcage.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{simple website generator}
  s.test_files = [
    "spec/document_path_spec.rb",
     "spec/export_spec.rb",
     "spec/import_spec.rb",
     "spec/loader_spec.rb",
     "spec/manifest_spec.rb",
     "spec/misc_spec.rb",
     "spec/smallcage_spec.rb",
     "spec/spec_helper.rb",
     "spec/update_list_spec.rb",
     "spec/update_spec.rb",
     "spec/uri_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

