Dir.chdir(File.dirname(__FILE__) + "/..")

require 'pathname'
require 'rubygems'
require 'smallcage'

FileList["_smc/rakelib/*.rake"].each {|f| load f }

task :default => :smcupdate

task :smcupdate do
  system "smc update"
end
